import { describe, it, expect } from "vitest";
import { isBalanced } from "./chemistry-balance/logic/parse";
import raw0 from "./bio-taxonomy/content/bio-taxonomy-questions.json";
import { cards as pool0 } from "./bio-taxonomy/content";
import raw1 from "./chemistry-balance/content/chemistry-balance-questions.json";
import { cards as pool1 } from "./chemistry-balance/content";
import raw2 from "./cloze-multi/content/cloze-multi-questions.json";
import { cards as pool2 } from "./cloze-multi/content";
import raw3 from "./english-blank/content/english-blank-questions.json";
import { cards as pool3 } from "./english-blank/content";
import raw4 from "./english-order/content/english-order-questions.json";
import { cards as pool4 } from "./english-order/content";
import raw5 from "./english-vocab-typing/content/english-vocab-typing-questions.json";
import { cards as pool5 } from "./english-vocab-typing/content";
import raw6 from "./english-word-match/content/english-word-match-questions.json";
import { cards as pool6 } from "./english-word-match/content";
import raw7 from "./factorization/content/factorization-questions.json";
import { cards as pool7 } from "./factorization/content";
import raw8 from "./genetics-punnett/content/genetics-punnett-questions.json";
import { cards as pool8 } from "./genetics-punnett/content";
import raw9 from "./history-timeline/content/history-timeline-questions.json";
import { cards as pool9 } from "./history-timeline/content";
import raw10 from "./image-hotspot/content/image-hotspot-questions.json";
import { cards as pool10 } from "./image-hotspot/content";
import raw11 from "./korean-pos-tagging/content/korean-pos-tagging-questions.json";
import { cards as pool11 } from "./korean-pos-tagging/content";
import raw12 from "./letter-assembly/content/letter-assembly-questions.json";
import { cards as pool12 } from "./letter-assembly/content";
import raw13 from "./math-graph-shift/content/math-graph-shift-questions.json";
import { cards as pool13 } from "./math-graph-shift/content";
import raw14 from "./math-quick-quiz/content/math-quick-quiz-questions.json";
import { cards as pool14 } from "./math-quick-quiz/content";
import raw15 from "./physics-vector/content/physics-vector-questions.json";
import { cards as pool15 } from "./physics-vector/content";
import raw16 from "./vocab-typing/content/vocab-typing-questions.json";
import { cards as pool16 } from "./vocab-typing/content";
const bundles = [{name:"bio-taxonomy", raw:raw0, pool:pool0},{name:"chemistry-balance", raw:raw1, pool:pool1},{name:"cloze-multi", raw:raw2, pool:pool2},{name:"english-blank", raw:raw3, pool:pool3},{name:"english-order", raw:raw4, pool:pool4},{name:"english-vocab-typing", raw:raw5, pool:pool5},{name:"english-word-match", raw:raw6, pool:pool6},{name:"factorization", raw:raw7, pool:pool7},{name:"genetics-punnett", raw:raw8, pool:pool8},{name:"history-timeline", raw:raw9, pool:pool9},{name:"image-hotspot", raw:raw10, pool:pool10},{name:"korean-pos-tagging", raw:raw11, pool:pool11},{name:"letter-assembly", raw:raw12, pool:pool12},{name:"math-graph-shift", raw:raw13, pool:pool13},{name:"math-quick-quiz", raw:raw14, pool:pool14},{name:"physics-vector", raw:raw15, pool:pool15},{name:"vocab-typing", raw:raw16, pool:pool16}];
describe("1700 supplied question cards",()=>{
 it("has exactly 100 per format and preserves runtime IDs",()=>{
  expect(bundles.reduce((n,b)=>n+b.raw.length,0)).toBe(1700);
  for(const b of bundles){expect(b.raw,b.name).toHaveLength(100);expect(new Set(b.raw.map(c=>c.id)).size,b.name).toBe(100);for(const c of b.raw)expect(b.pool.some(p=>p.id===c.id),c.id).toBe(true);expect(new Set(b.pool.map(c=>c.id)).size,b.name).toBe(b.pool.length);}
 });
 it("balances every supplied chemical equation",()=>{for(const c of raw1)expect(isBalanced(c.problem.reactants,c.problem.products),c.id).toBe(true);});
 it("has reachable vector sums",()=>{for(const c of raw15){const p=c.problem; for(const i of [0,1]){expect(p.resultant.components[i],c.id).toBe(p.vectors.reduce((n,v)=>n+v.components[i],0));expect(p.resultant.components[i],c.id).toBeGreaterThanOrEqual(-5);expect(p.resultant.components[i],c.id).toBeLessThanOrEqual(6);}}});
 it("has distinct choices in choice formats",()=>{for(const c of [...raw3,...raw14]){const ch=c.problem.choices;expect(new Set(ch).size,c.id).toBe(ch.length);}});
 it("keeps corrected answer keys and non-equivalent distractors",()=>{
  const eb=raw3.find(c=>c.id==="eb-draft-065")!.problem;expect(eb.choices[eb.correctIndex]).toBe("had left");
  const bad:Record<string,string>={"mqq-draft-025":"x-2","mqq-draft-033":"4-i²","mqq-draft-098":"√4","mqq-draft-100":"3|x|"};
  for(const [id,v] of Object.entries(bad))expect(raw14.find(c=>c.id===id)!.problem.choices,id).not.toContain(v);
 });
 it("uses real reactions with minimal reachable coefficients",()=>{const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;for(const c of raw1){const all=[...c.problem.reactants,...c.problem.products];expect(all.some(t=>t.formula==="Hg"||t.formula==="HgCO3"),c.id).toBe(false);expect(all.map(t=>t.coefficient).reduce(gcd),c.id).toBe(1);for(const t of all)expect(t.coefficient,c.id).toBeLessThanOrEqual(9);}});
 it("matches graph equations and keeps target curves visible",()=>{for(const c of raw13){const p=c.problem;const m=p.targetEquation.replace(/ /g,"").match(/^y=(-?\d*)(?:x|\(x([+-]\d+)\))²([+-]\d+)?$/);expect(m,c.id).not.toBeNull();const a=m![1]===""?1:m![1]==="-"?-1:Number(m![1]);expect([a,m![2]?-Number(m![2]):0,Number(m![3]??0)],c.id).toEqual([p.targetA,p.targetH,p.targetK]);let visible=0;for(let x=-5;x<=5;x+=0.1){const y=p.targetA*(x-p.targetH)**2+p.targetK;if(y>=-3&&y<=9)visible++;}expect(visible,c.id).toBeGreaterThan(10);}});
 it("has 100 distinct problems per format after removing ids",()=>{const strip=(v:unknown):unknown=>Array.isArray(v)?v.map(strip):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).filter(([k])=>!/^(id|slotId|correctCardId|categoryId)$/.test(k)).map(([k,x])=>[k,strip(x)])):v;for(const b of bundles){const keys=b.raw.map((c:any)=>JSON.stringify(strip(c.problem??c.polynomial)));expect(new Set(keys).size,b.name).toBe(100);}});
});
