// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT.
// 게임 추가/제거 시 `npm run gen:registry`로 재생성. predev/prebuild 훅이 자동 처리.
// 발견된 게임 (alphabetical): english-order, factorization, math-quick-quiz

import type { GameManifest } from "./types";

import englishOrder from "@/games/english-order/manifest";
import factorization from "@/games/factorization/manifest";
import mathQuickQuiz from "@/games/math-quick-quiz/manifest";

export const games: GameManifest[] = [
  englishOrder,
  factorization,
  mathQuickQuiz,
];
