// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT.
// 게임 추가/제거 시 `npm run gen:registry`로 재생성. predev/prebuild 훅이 자동 처리.
// 발견된 게임 (alphabetical): chemistry-balance, english-blank, english-order, english-word-match, factorization, history-timeline, math-graph-shift, math-quick-quiz, physics-vector, vocab-typing

import type { GameManifest } from "./types";

import chemistryBalance from "@/games/chemistry-balance/manifest";
import englishBlank from "@/games/english-blank/manifest";
import englishOrder from "@/games/english-order/manifest";
import englishWordMatch from "@/games/english-word-match/manifest";
import factorization from "@/games/factorization/manifest";
import historyTimeline from "@/games/history-timeline/manifest";
import mathGraphShift from "@/games/math-graph-shift/manifest";
import mathQuickQuiz from "@/games/math-quick-quiz/manifest";
import physicsVector from "@/games/physics-vector/manifest";
import vocabTyping from "@/games/vocab-typing/manifest";

export const games: GameManifest[] = [
  chemistryBalance,
  englishBlank,
  englishOrder,
  englishWordMatch,
  factorization,
  historyTimeline,
  mathGraphShift,
  mathQuickQuiz,
  physicsVector,
  vocabTyping,
];
