// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT.
// 게임 추가/제거 시 `bun run gen:registry`로 재생성. predev/prebuild 훅이 자동 처리.
// 발견된 게임 (alphabetical): chemistry-balance, custom-blank, custom-multiple-choice, custom-typing, custom-word-match, english-blank, english-order, english-vocab-typing, english-word-match, factorization, genetics-punnett, history-timeline, math-graph-shift, math-quick-quiz, physics-vector, vocab-typing

import type { GameManifest } from "./types";

import chemistryBalance from "@/games/chemistry-balance/manifest";
import customBlank from "@/games/custom-blank/manifest";
import customMultipleChoice from "@/games/custom-multiple-choice/manifest";
import customTyping from "@/games/custom-typing/manifest";
import customWordMatch from "@/games/custom-word-match/manifest";
import englishBlank from "@/games/english-blank/manifest";
import englishOrder from "@/games/english-order/manifest";
import englishVocabTyping from "@/games/english-vocab-typing/manifest";
import englishWordMatch from "@/games/english-word-match/manifest";
import factorization from "@/games/factorization/manifest";
import geneticsPunnett from "@/games/genetics-punnett/manifest";
import historyTimeline from "@/games/history-timeline/manifest";
import mathGraphShift from "@/games/math-graph-shift/manifest";
import mathQuickQuiz from "@/games/math-quick-quiz/manifest";
import physicsVector from "@/games/physics-vector/manifest";
import vocabTyping from "@/games/vocab-typing/manifest";

export const games: GameManifest[] = [
  chemistryBalance,
  customBlank,
  customMultipleChoice,
  customTyping,
  customWordMatch,
  englishBlank,
  englishOrder,
  englishVocabTyping,
  englishWordMatch,
  factorization,
  geneticsPunnett,
  historyTimeline,
  mathGraphShift,
  mathQuickQuiz,
  physicsVector,
  vocabTyping,
];
