#!/usr/bin/env tsx
/**
 * 풀림 게임즈 — Game Registry 자동 생성 스크립트.
 *
 * games/<id>/manifest.ts 를 glob 스캔해서 lib/games/registry.generated.ts 작성.
 *
 * 트리거:
 *   - bun run dev (predev 훅)
 *   - bun run build (prebuild 훅)
 *   - bun run gen:registry (수동)
 *
 * CI는 이 스크립트 실행 후 git diff --exit-code 로 manifest와 generated 일치 검증.
 *
 * 상세 설계: proc/plan/2026-05-08_parallel-game-architecture.md
 */

import fastGlob from "fast-glob";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const PROJECT_ROOT = resolve(process.cwd());
const OUTPUT_PATH = resolve(PROJECT_ROOT, "lib/games/registry.generated.ts");

// 게임 매니페스트 발견 — alphabetical 정렬로 머지 충돌 최소화
const manifestPaths = fastGlob
  .sync("games/*/manifest.ts", { cwd: PROJECT_ROOT })
  .sort();

const ids = manifestPaths
  .map((path) => {
    // games/<id>/manifest.ts → segments[1] 이 게임 id
    const segments = path.split("/");
    return segments[1];
  })
  .filter((id): id is string => Boolean(id));

// kebab-case id → camelCase identifier (예: 'quick-quiz' → 'quickQuiz')
function toIdentifier(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

const importLines = ids
  .map((id) => `import ${toIdentifier(id)} from "@/games/${id}/manifest";`)
  .join("\n");

const arrayEntries = ids.map((id) => `  ${toIdentifier(id)},`).join("\n");

const code = `// AUTO-GENERATED by scripts/generate-registry.ts — DO NOT EDIT.
// 게임 추가/제거 시 \`bun run gen:registry\`로 재생성. predev/prebuild 훅이 자동 처리.
// 발견된 게임 (alphabetical): ${ids.join(", ") || "(none)"}

import type { GameManifest } from "./types";

${importLines || "// (no manifests discovered)"}

export const games: GameManifest[] = [
${arrayEntries}
];
`;

writeFileSync(OUTPUT_PATH, code, "utf-8");

console.log(
  `✓ Generated registry with ${ids.length} game(s): ${ids.join(", ") || "(none)"}`,
);
